web2:
   image: tutum/apache-php
   container_name: apache-php
   ports:
     - "5000:80"
   links:
     - db2
   volumes:
     - ./app:/app

db2:
  image: mariadb
  container_name: mariadb2
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: database
    DB_ADMIN_PASS: pass
  ports:
    - "6000:3306"

phpmyadmin2:
  image: phpmyadmin/phpmyadmin
  container_name: admin2
  links: 
    - db2
  ports: 
    - "7000:80"